version: "3.9"
services:

  users_service:
    image: qmbo/users_service:0.0.1
    container_name: users_service
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq_mir_exchange
      SPRING_KAFKA_BOOTSTRAP-SERVERS: telegram_messages_sender_broker:49150
      SPRING_DATA_MONGODB_URI: mongodb://root:password@db_mir_exchange/mirexchange?authSource=admin
    depends_on:
      - rabbitmq
    restart: always
    networks:
      telegram_messages_sender_net:
        ipv4_address: 172.28.0.33

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq_mir_exchange'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      telegram_messages_sender_net:
        ipv4_address: 172.28.0.32

networks:
  telegram_messages_sender_net:
    external:
      name: telegram_messages_sender_net
